name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Generate xcodeproj
      run: swift package generate-xcodeproj
    - name: Build and Test
      run: xcodebuild test -destination 'name=My Mac' -scheme Ethereum
